### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by jkrue** [deNBI/OS_project_usage_exporter#7]
~The provided Dockerfile is outdated. It is based on Alpine 3.7 (current release is 3.11.x).~

**Comment by jkrue** [comment]
Should have a coffee before opening an issue. `python:3.7-alpine` is fine.

**Comment by pbelmann** [comment]
@vktrrdk  @eKatchko  I enabled debendabot for this repo. Could you please add config file as in our other repos.

**Comment by pbelmann** [comment]
Base Image can be updated: #13
@jkrue  No need for coffee!
